import { create } from 'zustand';

export type Language = 'en' | 'es' | 'fr' | 'it';

export const translations: Record<Language, Record<string, any>> = {
  en: {
    nav: {
      home: 'Home',
      discover: 'Discover',
      messages: 'Messages',
      profile: 'Profile',
      settings: 'Settings',
      adminPanel: 'Admin Panel',
      logout: 'Log Out',
      streaks: 'Streaks',
      foundingCircle: 'Founding Circle',
      foundingMember: 'Founding Member',
      rootedActive: 'Rooted Active',
      rootedDesc: 'You are actively verified. Show up locally to build real long-term community.',
    },
    landing: {
      signIn: 'Sign In',
      joinFounding: 'Join Founding Circle',
      heroTitle: 'A trust-first mentoring community.',
      heroSubtitle: 'Kindred is where students and professionals find values-aligned mentors, build genuine relationships, and stay rooted. Domain verified. Streak behavior-based. Reciprocity non-negotiable.',
      applyMembership: 'Apply for Membership',
      exploreMentors: 'Explore Mentors Demo',
      teaserTitle: "Who's Checked In Locally Right Now?",
      teaserDesc: 'Under our reciprocity contract, active locations and check-ins are restricted until you join the community and check in yourself.',
      lockedContract: 'Active Contract Locked',
      lockedDesc: 'Verify your email and complete a check-in to witness 12 local mentors and students checked-in around San Francisco.',
      signInUnlock: 'Sign In to Unlock',
      highTrustTitle: 'Built on Core High-Trust Mechanisms',
      domainVerifyTitle: 'Domain Verification',
      domainVerifyDesc: 'Connect your work or school email to build immediate credibility without uploading invasive government IDs.',
      checkInTitle: 'Check-In Reciprocity',
      checkInDesc: 'See who else is studying or working in local coffee shops. Surveillance-free: you must be checked-in to see others.',
      reputationTitle: 'Reputation Streaks',
      reputationDesc: 'Your reputation is calculated through check-in streaks, mentoring reviews, and help-swap consistency.',
      bilateralTitle: 'Bilateral Covenants',
      bilateralDesc: 'Seal mentoring relationships with signed Reciprocity Covenants. Sign electronically using our secure signature pad.',
      footerTerms: 'Privacy Charter',
      footerCovenant: 'Reciprocity Covenant',
      footerSafety: 'Safety Code',
    },
    home: {
      dashboardTitle: 'Local Reciprocity Feed',
      dashboardDesc: 'Show up locally to build long-term trust, increase streaking days, and unlock local interactions.',
      checkInHeading: 'Register Active Presence',
      checkInDesc: 'Let values-aligned community members see where you are working or studying today.',
      placeholderLocation: 'e.g. Sightglass Coffee, SF Public Library',
      placeholderNote: 'e.g. Working on React Architecture',
      buttonCheckIn: 'Check In & Show Up',
      activeCheckIn: 'Active Check-In',
      checkInNote: 'Note',
      checkedInSuccess: 'Checked In! Reciprocity Contract Unlocked.',
      checkedInStatus: 'Checked-in active locally',
      blurredCardHeading: 'Presence Details Secured',
      blurredCardDesc: 'Register your check-in to view and message other local active members.',
      checkInToReveal: 'Check in to Reveal Map',
      activeMentorsText: 'active local mentors Checked-in',
    },
    discover: {
      searchPlaceholder: 'Search by skills, company, or university...',
      skillsFilter: 'Skills Focus (All)',
      valuesFilter: 'Values Alignment (All)',
      mentorCircle: 'Mentorship Circles',
      requestMentoring: 'Request Mentoring',
      valuesMatch: 'Values Match',
      upcomingWorkshops: 'Upcoming Workshops & Circles',
      foundingOnly: 'Founding Circle Only',
      reserveSeat: 'Reserve Seat',
      reserved: 'Reserved ✓',
      free: 'Free',
    },
    messages: {
      proposeCovenant: 'Propose Reciprocity Covenant',
      covenantTitle: 'Draft Reciprocity Covenant',
      teachSkill: 'Skill to Teach',
      learnSkill: 'Skill to Learn',
      cadence: 'Meeting Cadence',
      weekly: 'Weekly check-in',
      biweekly: 'Bi-weekly check-in',
      monthly: 'Monthly check-in',
      duration: 'Duration',
      oneMonth: '1 Month Sprout',
      threeMonths: '3 Months Seedling',
      sixMonths: '6 Months Oak',
      signaturePad: 'Bilateral Signature Initials',
      clearSignature: 'Clear Pad',
      submitProposal: 'Submit Bilateral Proposal',
      pendingCovenant: 'Proposed Covenant (Pending Acceptance)',
      acceptSwap: 'Accept Swap & Sign',
      declineSwap: 'Decline',
      signedCovenant: 'Sealed Reciprocity Covenant',
      signInstructions: 'Draw your initials inside the canvas signature pad to finalize.',
    },
    profile: {
      verifiedCredentials: 'Verified Credentials',
      foundingMemberCircle: 'Founding Member Circle',
      viewCertButton: '📜 View Founding Certificate',
      collaborationRewards: 'Collaboration Rewards',
      rewardsDesc: 'Earn custom badges and reputation multipliers by showing up locally.',
      consistentSteward: 'Consistent Steward',
      consistentDesc: 'Reach a 5-day check-in streak to unlock.',
      reciprocityChampion: 'Reciprocity Champion',
      reciprocityDesc: 'Sign & complete 1 covenant to unlock.',
      rewardsInfo: 'Unlocking rewards boosts discoverability in local search by 25% and expands Founding Circle voting weight.',
      trustScoreHeading: 'Covenant Trust Score',
      trustScoreDesc: 'Calculated in real time through verified streaking and contracts.',
      feedbackRatingWeight: 'Feedback Rating Weight',
      checkInStreakWeight: 'Streak Weight',
      swapsWeight: 'Swaps Weight',
      integritySignal: 'Verified work/school credentials instantly provide a one-time trust multiplier (+0.3). Higher trust scores increase matching alignment weight.',
      sandboxReviewTitle: 'Sandbox Review Simulator',
      sandboxReviewDesc: 'Submit simulated peer feedback to watch the averages and Trust Score recalculate in real-time!',
      ratingLabel: 'Rating Star',
      commentLabel: 'Peer Feedback Comment',
      submitReview: 'Submit Review',
      reviewFeedTitle: 'Peer Feedback Feed',
      noReviews: 'No peer reviews submitted yet. Submit a sandbox feedback above to verify!',
      certificateTitle: 'Covenant of Alignment',
      certificateSubtitle: 'This document serves as testament that',
      certificatePledge: 'has been admitted into the Kindred Founding Circle as Member #{num} on this day of enrollment, pledged to reciprocity, collective learning, and nurturing our shared stewardship.',
      certificateGovernance: 'Kindred Governance',
      certificateCircleMember: 'Founding Circle Member',
      printCert: 'Print',
    },
    settings: {
      accountSettings: 'Account Settings',
      settingsDesc: 'Configure your credentials, domain email badges, and notifications.',
      verifyProfessional: 'Verify Professional Credential',
      verifyAcademic: 'Verify Academic Credential',
      verifyBusiness: 'Verify Local Business Owner',
      companyEmail: 'Company Email Address',
      univEmail: 'University Email Address',
      businessEmail: 'Business Email Address',
      businessName: 'Business Name (Optional)',
      businessRegNum: 'Business Registration Number (Optional)',
      buttonVerifyWork: 'Verify Work Email',
      buttonVerifySchool: 'Verify School Email',
      buttonVerifyBusiness: 'Verify Business Email',
      verificationComplete: 'Verification Complete ✓',
      domainVerified: 'is domain verified.',
      securityTitle: 'Security & 2FA',
      preferencesTitle: 'Preferences',
      emailAlerts: 'Email Alerts',
      checkInAlerts: 'Check-In Broadcasts',
      messagesAlerts: 'Mentoring Messages',
    }
  },
  es: {
    nav: {
      home: 'Inicio',
      discover: 'Descubrir',
      messages: 'Mensajes',
      profile: 'Perfil',
      settings: 'Configuración',
      adminPanel: 'Panel de Admin',
      logout: 'Cerrar Sesión',
      streaks: 'Rachas',
      foundingCircle: 'Círculo Fundador',
      foundingMember: 'Miembro Fundador',
      rootedActive: 'Activo y Verificado',
      rootedDesc: 'Estás verificado activamente. Preséntate localmente para construir una comunidad real a largo plazo.',
    },
    landing: {
      signIn: 'Iniciar Sesión',
      joinFounding: 'Unirse al Círculo Fundador',
      heroTitle: 'Una comunidad de mentoría de confianza.',
      heroSubtitle: 'Kindred es donde los estudiantes y profesionales encuentran mentores alineados con sus valores, construyen relaciones genuinas y se mantienen conectados. Dominio verificado. Basado en la constancia de rachas. Reciprocidad no negociable.',
      applyMembership: 'Solicitar Membresía',
      exploreMentors: 'Explorar Demo de Mentores',
      teaserTitle: '¿Quién se ha registrado localmente ahora mismo?',
      teaserDesc: 'Bajo nuestro contrato de reciprocidad, las ubicaciones activas y los registros están restringidos hasta que te unas a la comunidad y te registres tú mismo.',
      lockedContract: 'Contrato Activo Bloqueado',
      lockedDesc: 'Verifica tu correo electrónico y completa un registro para ver 12 mentores y estudiantes locales registrados alrededor de San Francisco.',
      signInUnlock: 'Iniciar Sesión para Desbloquear',
      highTrustTitle: 'Basado en Mecanismos de Alta Confianza',
      domainVerifyTitle: 'Verificación de Dominio',
      domainVerifyDesc: 'Conecta tu correo de trabajo o escuela para construir credibilidad inmediata sin subir documentos de identidad invasivos.',
      checkInTitle: 'Reciprocidad de Registros',
      checkInDesc: 'Mira quién más está estudiando o trabajando en cafeterías locales. Sin vigilancia: debes registrarte para ver a los demás.',
      reputationTitle: 'Rachas de Reputación',
      reputationDesc: 'Tu reputación se calcula mediante rachas de registro, comentarios de mentoría y la consistencia en el intercambio de ayuda.',
      bilateralTitle: 'Pactos Bilaterales',
      bilateralDesc: 'Sella relaciones de mentoría con Pactos de Reciprocidad firmados electrónicamente usando nuestro panel de firma seguro.',
      footerTerms: 'Carta de Privacidad',
      footerCovenant: 'Pacto de Reciprocidad',
      footerSafety: 'Código de Seguridad',
    },
    home: {
      dashboardTitle: 'Feed de Reciprocidad Local',
      dashboardDesc: 'Preséntate localmente para generar confianza a largo plazo, aumentar los días de racha y desbloquear interacciones locales.',
      checkInHeading: 'Registrar Presencia Activa',
      checkInDesc: 'Permite que los miembros de la comunidad alineados con tus valores vean dónde estás trabajando o estudiando hoy.',
      placeholderLocation: 'ej. Sightglass Coffee, Biblioteca Pública de SF',
      placeholderNote: 'ej. Trabajando en la arquitectura de React',
      buttonCheckIn: 'Registrarse y Mostrarse',
      activeCheckIn: 'Registro Activo',
      checkInNote: 'Nota',
      checkedInSuccess: '¡Registrado! Contrato de Reciprocidad Desbloqueado.',
      checkedInStatus: 'Check-in activo localmente',
      blurredCardHeading: 'Detalles de Presencia Asegurados',
      blurredCardDesc: 'Registra tu check-in para ver y enviar mensajes a otros miembros activos locales.',
      checkInToReveal: 'Registrarse para Revelar Mapa',
      activeMentorsText: 'mentores locales activos registrados',
    },
    discover: {
      searchPlaceholder: 'Buscar por habilidades, empresa o universidad...',
      skillsFilter: 'Habilidades (Todas)',
      valuesFilter: 'Alineación de Valores (Todos)',
      mentorCircle: 'Círculos de Mentoría',
      requestMentoring: 'Solicitar Mentoría',
      valuesMatch: 'Coincidencia de Valores',
      upcomingWorkshops: 'Próximos Talleres y Círculos',
      foundingOnly: 'Solo Círculo Fundador',
      reserveSeat: 'Reservar Asiento',
      reserved: 'Reservado ✓',
      free: 'Gratis',
    },
    messages: {
      proposeCovenant: 'Proponer Pacto de Reciprocidad',
      covenantTitle: 'Borrador de Pacto de Reciprocidad',
      teachSkill: 'Habilidad para Enseñar',
      learnSkill: 'Habilidad para Aprender',
      cadence: 'Frecuencia de Encuentros',
      weekly: 'Control semanal',
      biweekly: 'Control quincenal',
      monthly: 'Control mensual',
      duration: 'Duración',
      oneMonth: 'Brote de 1 Mes',
      threeMonths: 'Plántula de 3 Meses',
      sixMonths: 'Roble de 6 Meses',
      signaturePad: 'Iniciales de Firma Bilateral',
      clearSignature: 'Limpiar Panel',
      submitProposal: 'Enviar Propuesta Bilateral',
      pendingCovenant: 'Pacto Propuesto (Pendiente de Aceptación)',
      acceptSwap: 'Aceptar Intercambio y Firmar',
      declineSwap: 'Rechazar',
      signedCovenant: 'Pacto de Reciprocidad Sellado',
      signInstructions: 'Dibuja tus iniciales dentro del panel de firma para finalizar.',
    },
    profile: {
      verifiedCredentials: 'Credenciales Verificadas',
      foundingMemberCircle: 'Círculo de Miembros Fundadores',
      viewCertButton: '📜 Ver Certificado Fundador',
      collaborationRewards: 'Premios de Colaboración',
      rewardsDesc: 'Gana insignias personalizadas y multiplicadores de reputación al presentarte localmente.',
      consistentSteward: 'Administrador Constante',
      consistentDesc: 'Alcanza una racha de registro de 5 días para desbloquear.',
      reciprocityChampion: 'Campeón de Reciprocidad',
      reciprocityDesc: 'Firma y completa 1 pacto para desbloquear.',
      rewardsInfo: 'Desbloquear premios aumenta la visibilidad en búsquedas locales en un 25% y expande el peso de voto en el Círculo Fundador.',
      trustScoreHeading: 'Puntuación de Confianza Covenant',
      trustScoreDesc: 'Calculada en tiempo real mediante rachas verificadas y contratos.',
      feedbackRatingWeight: 'Peso de Calificación de Feedback',
      checkInStreakWeight: 'Peso de Racha de Registro',
      swapsWeight: 'Peso de Intercambios',
      integritySignal: 'Las credenciales verificadas de trabajo/escuela otorgan instantáneamente un multiplicador de confianza único (+0.3). Puntuaciones de confianza más altas aumentan el peso de alineación.',
      sandboxReviewTitle: 'Simulador de Reseña Sandbox',
      sandboxReviewDesc: '¡Envía comentarios simulados para ver los promedios y la Puntuación de Confianza recalcularse en tiempo real!',
      ratingLabel: 'Estrella de Calificación',
      commentLabel: 'Comentario de Feedback de Pares',
      submitReview: 'Enviar Reseña',
      reviewFeedTitle: 'Feed de Feedback de Pares',
      noReviews: 'No se han enviado reseñas todavía. ¡Envía un feedback de prueba arriba para verificar!',
      certificateTitle: 'Pacto de Alineación',
      certificateSubtitle: 'Este documento sirve como testimonio de que',
      certificatePledge: 'ha sido admitido en el Círculo Fundador de Kindred como Miembro #{num} en este día de inscripción, comprometido con la reciprocidad, el aprendizaje colectivo y el fomento de nuestra gestión compartida.',
      certificateGovernance: 'Gobernanza de Kindred',
      certificateCircleMember: 'Miembro del Círculo Fundador',
      printCert: 'Imprimir',
    },
    settings: {
      accountSettings: 'Configuración de Cuenta',
      settingsDesc: 'Configura tus credenciales, insignias de correo de dominio y notificaciones.',
      verifyProfessional: 'Verificar Credencial Profesional',
      verifyAcademic: 'Verificar Credencial Académica',
      verifyBusiness: 'Verificar Propietario de Negocio Local',
      companyEmail: 'Dirección de Correo de la Empresa',
      univEmail: 'Dirección de Correo de la Universidad',
      businessEmail: 'Dirección de Correo Comercial',
      businessName: 'Nombre de la Empresa (Opcional)',
      businessRegNum: 'Número de Registro de la Empresa (Opcional)',
      buttonVerifyWork: 'Verificar Correo de Trabajo',
      buttonVerifySchool: 'Verificar Correo Escolar',
      buttonVerifyBusiness: 'Verificar Correo Comercial',
      verificationComplete: 'Verificación Completa ✓',
      domainVerified: 'está verificado por dominio.',
      securityTitle: 'Seguridad y 2FA',
      preferencesTitle: 'Preferencias',
      emailAlerts: 'Alertas de Correo',
      checkInAlerts: 'Transmisiones de Registro',
      messagesAlerts: 'Mensajes de Mentoría',
    }
  },
  fr: {
    nav: {
      home: 'Accueil',
      discover: 'Découvrir',
      messages: 'Messages',
      profile: 'Profil',
      settings: 'Paramètres',
      adminPanel: 'Panneau Admin',
      logout: 'Déconnexion',
      streaks: 'Séries',
      foundingCircle: 'Cercle Fondateur',
      foundingMember: 'Membre Fondateur',
      rootedActive: 'Vérifié Actif',
      rootedDesc: 'Vous êtes activement vérifié. Présentez-vous localement pour bâtir une véritable communauté à long terme.',
    },
    landing: {
      signIn: 'Se Connecter',
      joinFounding: 'Rejoindre le Cercle Fondateur',
      heroTitle: 'Une communauté de mentorat basée sur la confiance.',
      heroSubtitle: "Kindred est le lieu où les étudiants et les professionnels trouvent des mentors partageant les mêmes valeurs, construisent des relations authentiques et restent connectés. Domaine vérifié. Basé sur l'assiduité. Réciprocité non négociable.",
      applyMembership: "Demander l'Adhésion",
      exploreMentors: 'Explorer la Démo Mentors',
      teaserTitle: 'Qui est enregistré localement en ce moment ?',
      teaserDesc: 'Selon notre contrat de réciprocité, les emplacements actifs et les enregistrements sont limités jusqu\'à ce que vous rejoigniez la communauté et que vous vous enregistriez vous-même.',
      lockedContract: 'Contrat Actif Verrouillé',
      lockedDesc: 'Vérifiez votre e-mail et effectuez un enregistrement pour voir 12 mentors et étudiants locaux enregistrés autour de San Francisco.',
      signInUnlock: 'Se Connecter pour Déverrouiller',
      highTrustTitle: 'Bâti sur des Mécanismes de Haute Confiance',
      domainVerifyTitle: 'Vérification de Domaine',
      domainVerifyDesc: 'Connectez votre e-mail professionnel ou universitaire pour renforcer immédiatement votre crédibilité sans fournir de pièces d\'identité invasives.',
      checkInTitle: 'Réciprocité d\'Enregistrement',
      checkInDesc: 'Découvrez qui d\'autre étudie ou travaille dans les cafés locaux. Sans surveillance : vous devez vous enregistrer pour voir les autres.',
      reputationTitle: 'Séries de Réputation',
      reputationDesc: 'Votre réputation est calculée en fonction de vos séries d\'enregistrements, des évaluations de mentorat et de l\'assiduité aux échanges d\'aide.',
      bilateralTitle: 'Pactes Bilatéraux',
      bilateralDesc: 'Scellez vos relations de mentorat par des Pactes de Réciprocité signés électroniquement via notre écran de signature sécurisé.',
      footerTerms: 'Charte de Confidentialité',
      footerCovenant: 'Pacte de Réciprocité',
      footerSafety: 'Code de Sécurité',
    },
    home: {
      dashboardTitle: 'Fil de Réciprocité Locale',
      dashboardDesc: 'Présentez-vous localement pour instaurer une confiance à long terme, augmenter vos jours de série et débloquer des interactions locales.',
      checkInHeading: 'Enregistrer votre Présence Active',
      checkInDesc: 'Permettez aux membres partageant vos valeurs de voir où vous travaillez ou étudiez aujourd\'hui.',
      placeholderLocation: 'ex. Sightglass Coffee, Bibliothèque Publique de SF',
      placeholderNote: 'ex. Travail sur l\'architecture React',
      buttonCheckIn: 'S\'enregistrer et Se Présenter',
      activeCheckIn: 'Enregistrement Actif',
      checkInNote: 'Note',
      checkedInSuccess: 'Enregistré ! Contrat de Réciprocité Déverrouillé.',
      checkedInStatus: 'Check-in actif localement',
      blurredCardHeading: 'Détails de Présence Sécurisés',
      blurredCardDesc: 'Enregistrez votre check-in pour voir et envoyer des messages aux autres membres locaux actifs.',
      checkInToReveal: 'S\'enregistrer pour Révéler la Carte',
      activeMentorsText: 'mentors locaux actifs enregistrés',
    },
    discover: {
      searchPlaceholder: 'Rechercher par compétences, entreprise ou université...',
      skillsFilter: 'Compétences (Toutes)',
      valuesFilter: 'Alignement des Valeurs (Tous)',
      mentorCircle: 'Cercles de Mentorat',
      requestMentoring: 'Demander un Mentorat',
      valuesMatch: 'Correspondance des Valeurs',
      upcomingWorkshops: 'Ateliers et Cercles à Venir',
      foundingOnly: 'Cercle Fondateur Uniquement',
      reserveSeat: 'Réserver un Siège',
      reserved: 'Réservé ✓',
      free: 'Gratuit',
    },
    messages: {
      proposeCovenant: 'Proposer un Pacte de Réciprocité',
      covenantTitle: 'Projet de Pacte de Réciprocité',
      teachSkill: 'Compétence à Enseigner',
      learnSkill: 'Compétence à Apprendre',
      cadence: 'Fréquence des Rencontres',
      weekly: 'Suivi hebdomadaire',
      biweekly: 'Suivi bimensuel',
      monthly: 'Suivi mensuel',
      duration: 'Durée',
      oneMonth: 'Pousse de 1 Mois',
      threeMonths: 'Plant de 3 Mois',
      sixMonths: 'Chêne de 6 Mois',
      signaturePad: 'Initiales de Signature Bilatérale',
      clearSignature: 'Effacer l\'Écran',
      submitProposal: 'Soumettre la Proposition Bilatérale',
      pendingCovenant: 'Pacte Proposé (En Attente d\'Acceptation)',
      acceptSwap: 'Accepter l\'Échange et Signer',
      declineSwap: 'Refuser',
      signedCovenant: 'Pacte de Réciprocité Scellé',
      signInstructions: 'Dessinez vos initiales dans l\'écran de signature pour finaliser.',
    },
    profile: {
      verifiedCredentials: 'Identifiants Vérifiés',
      foundingMemberCircle: 'Cercle des Membres Fondateurs',
      viewCertButton: '📜 Voir le Certificat Fondateur',
      collaborationRewards: 'Récompenses de Collaboration',
      rewardsDesc: 'Gagnez des badges personnalisés et des multiplicateurs de réputation en vous présentant localement.',
      consistentSteward: 'Gestionnaire Assidu',
      consistentDesc: 'Atteignez une série de 5 jours d\'enregistrement pour débloquer.',
      reciprocityChampion: 'Champion de la Réciprocité',
      reciprocityDesc: 'Signez et complétez 1 pacte pour déverrouiller.',
      rewardsInfo: 'Débloquer des récompenses augmente la visibilité dans les recherches locales de 25% et élargit le poids de vote au sein du Cercle Fondateur.',
      trustScoreHeading: 'Score de Confiance Covenant',
      trustScoreDesc: 'Calculé en temps réel grâce aux séries vérifiées et aux contrats.',
      feedbackRatingWeight: 'Poids de l\'Évaluation de Feedback',
      checkInStreakWeight: 'Poids de la Série d\'Enregistrements',
      swapsWeight: 'Poids des Échanges',
      integritySignal: 'Les identifiants professionnels/universitaires vérifiés offrent immédiatement un multiplicateur de confiance unique (+0.3). Les scores de confiance plus élevés augmentent le poids d\'alignement.',
      sandboxReviewTitle: 'Simulateur d\'Évaluation Sandbox',
      sandboxReviewDesc: 'Soumettez des évaluations simulées pour voir les moyennes et le score de confiance se recalculer en temps réel !',
      ratingLabel: 'Étoile d\'Évaluation',
      commentLabel: 'Commentaire de Feedback de Pair',
      submitReview: 'Soumettre l\'Évaluation',
      reviewFeedTitle: 'Flux de Feedback des Pairs',
      noReviews: 'Aucune évaluation de pair soumise pour le moment. Soumettez une évaluation ci-dessus pour vérifier !',
      certificateTitle: 'Pacte d\'Alignement',
      certificateSubtitle: 'Ce document sert de témoignage que',
      certificatePledge: 'a été admis au Cercle Fondateur de Kindred en tant que Membre #{num} en ce jour d\'inscription, engagé dans la réciprocité, l\'apprentissage collectif et le développement de notre intendance partagée.',
      certificateGovernance: 'Gouvernance de Kindred',
      certificateCircleMember: 'Membre du Cercle Fondateur',
      printCert: 'Imprimer',
    },
    settings: {
      accountSettings: 'Paramètres du Compte',
      settingsDesc: 'Configurez vos identifiants, vos badges d\'e-mail de domaine et vos notifications.',
      verifyProfessional: 'Vérifier les Identifiants Professionnels',
      verifyAcademic: 'Vérifier les Identifiants Académiques',
      verifyBusiness: 'Vérifier Propriétaire d\'Entreprise Locale',
      companyEmail: 'Adresse E-mail de l\'Entreprise',
      univEmail: 'Adresse E-mail de l\'Université',
      businessEmail: 'Adresse E-mail Commerciale',
      businessName: 'Nom de l\'Entreprise (Optionnel)',
      businessRegNum: 'Numéro d\'Enregistrement de l\'Entreprise (Optionnel)',
      buttonVerifyWork: 'Vérifier l\'E-mail Professionnel',
      buttonVerifySchool: 'Vérifier l\'E-mail Universitaire',
      buttonVerifyBusiness: 'Vérifier l\'E-mail Commercial',
      verificationComplete: 'Vérification Complète ✓',
      domainVerified: 'est vérifié par domaine.',
      securityTitle: 'Sécurité et 2FA',
      preferencesTitle: 'Préférences',
      emailAlerts: 'Alertes E-mail',
      checkInAlerts: 'Diffusions d\'Enregistrement',
      messagesAlerts: 'Messages de Mentorat',
    }
  },
  it: {
    nav: {
      home: 'Home',
      discover: 'Scopri',
      messages: 'Messaggi',
      profile: 'Profilo',
      settings: 'Impostazioni',
      adminPanel: 'Pannello Admin',
      logout: 'Esci',
      streaks: 'Strisce',
      foundingCircle: 'Cerchio Fondatore',
      foundingMember: 'Membro Fondatore',
      rootedActive: 'Verificato Attivo',
      rootedDesc: 'Sei verificato attivamente. Fatti vedere a livello locale per costruire una vera comunità a lungo termine.',
    },
    landing: {
      signIn: 'Accedi',
      joinFounding: 'Unisciti al Cerchio Fondatore',
      heroTitle: 'Una comunità di mentoring basata sulla fiducia.',
      heroSubtitle: 'Kindred è il luogo in cui gli studenti e i professionisti trovano mentori allineati ai loro valori, costruiscono relazioni autentiche e rimangono connessi. Dominio verificato. Basato sull\'assiduità. Reciprocità non negoziabile.',
      applyMembership: 'Richiedi l\'Adesione',
      exploreMentors: 'Esplora Demo Mentori',
      teaserTitle: 'Chi ha effettuato il check-in locale in questo momento?',
      teaserDesc: 'In base al nostro contratto di reciprocità, le posizioni attive e i check-in sono limitati fino a quando non ti unisci alla comunità e fai il check-in tu stesso.',
      lockedContract: 'Contratto Attivo Bloccato',
      lockedDesc: 'Verifica la tua email e completa un check-in per vedere 12 mentori e studenti locali registrati a San Francisco.',
      signInUnlock: 'Accedi per Sbloccare',
      highTrustTitle: 'Basato su Meccanismi ad Alta Fiducia',
      domainVerifyTitle: 'Verifica del Dominio',
      domainVerifyDesc: 'Collega la tua email di lavoro o universitaria per costruire credibilità immediata senza caricare documenti d\'identità invasivi.',
      checkInTitle: 'Reciprocità di Check-In',
      checkInDesc: 'Scopri chi altro sta studiando o lavorando nelle caffetterie locali. Senza sorveglianza: devi fare il check-in per vedere gli altri.',
      reputationTitle: 'Strisce di Reputazione',
      reputationDesc: 'La tua reputazione viene calcolata in base alle tue strisce di check-in, alle valutazioni di mentoring e alla costanza nello scambio di aiuto.',
      bilateralTitle: 'Patti Bilaterali',
      bilateralDesc: 'Sigilla le relazioni di mentoring con Patti di Reciprocità firmati elettronicamente utilizzando il nostro pannello di firma sicuro.',
      footerTerms: 'Carta della Privacy',
      footerCovenant: 'Patto di Reciprocità',
      footerSafety: 'Codice di Sicurezza',
    },
    home: {
      dashboardTitle: 'Feed di Reciprocità Locale',
      dashboardDesc: 'Fatti vedere a livello locale per costruire una fiducia a lungo termine, aumentare i giorni di striscia e sbloccare le interazioni locali.',
      checkInHeading: 'Registra Presenza Attiva',
      checkInDesc: 'Consenti ai membri della comunità allineati ai tuoi valori di vedere dove stai lavorando o studiando oggi.',
      placeholderLocation: 'es. Sightglass Coffee, Biblioteca Pubblica di SF',
      placeholderNote: 'es. Lavorando all\'architettura React',
      buttonCheckIn: 'Fai Check-In e Mostrati',
      activeCheckIn: 'Check-In Attivo',
      checkInNote: 'Nota',
      checkedInSuccess: 'Check-in effettuato! Contratto di Reciprocità Sbloccato.',
      checkedInStatus: 'Check-in attivo localmente',
      blurredCardHeading: 'Dettagli sulla Presenza Protetti',
      blurredCardDesc: 'Fai check-in per vedere e inviare messaggi agli altri membri attivi locali.',
      checkInToReveal: 'Fai Check-in per Rivelare la Mappa',
      activeMentorsText: 'mentori locali attivi registrati',
    },
    discover: {
      searchPlaceholder: 'Cerca per competenze, azienda o università...',
      skillsFilter: 'Competenze (Tutte)',
      valuesFilter: 'Allineamento Valori (Tutti)',
      mentorCircle: 'Cerchi di Mentoring',
      requestMentoring: 'Richiedi Mentoring',
      valuesMatch: 'Corrispondenza Valori',
      upcomingWorkshops: 'Prossimi Workshop e Cerchi',
      foundingOnly: 'Solo Cerchio Fondatore',
      reserveSeat: 'Riserva Posto',
      reserved: 'Riservato ✓',
      free: 'Gratuito',
    },
    messages: {
      proposeCovenant: 'Proponi Patto di Reciprocidad',
      covenantTitle: 'Bozza di Patto di Reciprocità',
      teachSkill: 'Competenza da Insegnare',
      learnSkill: 'Competenza da Apprendere',
      cadence: 'Frequenza degli Incontri',
      weekly: 'Controllo settimanale',
      biweekly: 'Controllo bisettimanale',
      monthly: 'Controllo mensile',
      duration: 'Durata',
      oneMonth: 'Germoglio di 1 Mese',
      threeMonths: 'Piantina di 3 Mesi',
      sixMonths: 'Quercia di 6 Mesi',
      signaturePad: 'Iniziali di Firma Bilaterale',
      clearSignature: 'Cancella Pannello',
      submitProposal: 'Invia Proposta Bilaterale',
      pendingCovenant: 'Patto Proposto (In Attesa di Accettazione)',
      acceptSwap: 'Accetta lo Scambio e Firma',
      declineSwap: 'Rifiuta',
      signedCovenant: 'Patto di Reciprocità Sigillato',
      signInstructions: 'Disegna le tue iniziali nel pannello di firma per completare.',
    },
    profile: {
      verifiedCredentials: 'Credenziali Verificate',
      foundingMemberCircle: 'Cerchio dei Membri Fondatori',
      viewCertButton: '📜 Visualizza Certificato Fondatore',
      collaborationRewards: 'Premi di Collaborazione',
      rewardsDesc: 'Guadagna badge personalizzati e moltiplicatori di reputazione facendoti vedere localmente.',
      consistentSteward: 'Amministratore Costante',
      consistentDesc: 'Raggiungi una striscia di check-in di 5 giorni per sbloccare.',
      reciprocityChampion: 'Campione della Reciprocità',
      reciprocityDesc: 'Firma e completa 1 patto per sbloccare.',
      rewardsInfo: 'Sbloccare i premi aumenta la visibilità nelle ricerche locali del 25% e amplia il peso di voto nel Cerchio Fondatore.',
      trustScoreHeading: 'Punteggio di Fiducia Covenant',
      trustScoreDesc: 'Calcolato in tempo reale tramite strisce verificate e contratti.',
      feedbackRatingWeight: 'Peso della Valutazione di Feedback',
      checkInStreakWeight: 'Peso della Striscia di Check-In',
      swapsWeight: 'Peso degli Scambi',
      integritySignal: 'Le credenziali verificate di lavoro/università offrono immediatamente un moltiplicatore di fiducia unico (+0.3). I punteggi di fiducia più elevati aumentano il peso dell\'allineamento.',
      sandboxReviewTitle: 'Simulatore di Recensioni Sandbox',
      sandboxReviewDesc: 'Invia feedback simulati per vedere le medie e il Punteggio di Fiducia ricalcolarsi in tempo real!',
      ratingLabel: 'Stella di Valutazione',
      commentLabel: 'Commento di Feedback del Peer',
      submitReview: 'Invia Recensione',
      reviewFeedTitle: 'Feed di Feedback dei Peer',
      noReviews: 'Nessuna recensione peer inviata al momento. Invia una recensione sopra per verificare!',
      certificateTitle: 'Patto di Allineamento',
      certificateSubtitle: 'Questo documento funge da testimonianza che',
      certificatePledge: 'è stato ammesso nel Cerchio Fondatore di Kindred come Membro #{num} in questo giorno di iscrizione, impegnato nella reciprocità, nell\'apprendimento collettivo e nello sviluppo della nostra gestione condivisa.',
      certificateGovernance: 'Governance di Kindred',
      certificateCircleMember: 'Membro del Cerchio Fondatore',
      printCert: 'Stampa',
    },
    settings: {
      accountSettings: 'Impostazioni Account',
      settingsDesc: 'Configura le tue credenziali, i badge email del dominio e le notifiche.',
      verifyProfessional: 'Verifica Credenziale Professionale',
      verifyAcademic: 'Verifica Credenziale Accademica',
      verifyBusiness: 'Verifica Proprietario di Attività Locale',
      companyEmail: 'Indirizzo Email dell\'Azienda',
      univEmail: 'Indirizzo Email dell\'Università',
      businessEmail: 'Indirizzo Email Commerciale',
      businessName: 'Nome dell\'Attività (Opzionale)',
      businessRegNum: 'Numero di Registrazione dell\'Attività (Opzionale)',
      buttonVerifyWork: 'Verifica Email di Lavoro',
      buttonVerifySchool: 'Verifica Email Scolastica',
      buttonVerifyBusiness: 'Verifica Email Commerciale',
      verificationComplete: 'Verifica Completata ✓',
      domainVerified: 'è verificato per dominio.',
      securityTitle: 'Sicurezza e 2FA',
      preferencesTitle: 'Preferenze',
      emailAlerts: 'Avvisi Email',
      checkInAlerts: 'Trasmissioni di Check-In',
      messagesAlerts: 'Messaggi di Mentoring',
    }
  }
};

interface LanguageState {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (path: string, num?: number) => string;
}

export const useLanguageStore = create<LanguageState>()((set, get) => ({
  language: (localStorage.getItem('kindred_lang') as Language) || 'en',
  
  setLanguage: (language: Language) => {
    localStorage.setItem('kindred_lang', language);
    set({ language });
  },

  t: (path: string, num?: number) => {
    const lang = get().language;
    const dict = translations[lang] || translations['en'];
    
    // Split nested dot notation, e.g. "landing.heroTitle"
    const keys = path.split('.');
    let current: any = dict;
    
    for (const key of keys) {
      if (current && typeof current === 'object' && key in current) {
        current = current[key];
      } else {
        // Fallback to English dictionary if not found in active language
        let fallbackDict: any = translations['en'];
        let foundFallback = true;
        for (const fKey of keys) {
          if (fallbackDict && typeof fallbackDict === 'object' && fKey in fallbackDict) {
            fallbackDict = fallbackDict[fKey];
          } else {
            foundFallback = false;
            break;
          }
        }
        return foundFallback ? (typeof fallbackDict === 'string' ? fallbackDict.replace('{num}', String(num || 0)) : path) : path;
      }
    }
    
    if (typeof current === 'string') {
      return current.replace('{num}', String(num || 0));
    }
    
    return path;
  }
}));
